:categories:
  - :name: 'world'
    :seeds:
      - :url: 'http://en.wikipedia.org/wiki/World'
        :selector: '.mw-content-ltr'
      - :url: 'http://en.wikipedia.org/wiki/List_of_sovereign_states'
        :selector: '.mw-content-ltr'
      - :url: 'http://en.wikipedia.org/wiki/Universe'
        :selector: '.mw-content-ltr'
      - :url: 'http://en.wikipedia.org/wiki/Globe'
        :selector: '.mw-content-ltr'
  - :name: 'africa'
    :seeds:
      - :url: 'http://en.wikipedia.org/wiki/Africa'
        :selector: '.mw-content-ltr'
      - :url: 'http://en.wikipedia.org/wiki/List_of_African_countries_and_territories'
        :selector: '.mw-content-ltr'
  - :name: 'economy'
    :seeds:
      - :url: 'http://en.wikipedia.org/wiki/Economy'
        :selector: '.mw-content-ltr'
      - :url: 'http://en.wikipedia.org/wiki/Finance'
        :selector: '.mw-content-ltr'
      - :url: 'http://en.wikipedia.org/wiki/Business'
        :selector: '.mw-content-ltr'
  - :name: 'science'
    :seeds:
      - :url: 'http://en.wikipedia.org/wiki/Science'
        :selector: '.mw-content-ltr'
      - :url: 'http://en.wikipedia.org/wiki/Technology'
        :selector: '.mw-content-ltr'
  - :name: 'sport'
    :seeds:
      - :url: 'http://en.wikipedia.org/wiki/Sport'
        :selector: '.mw-content-ltr'
      - :url: 'http://en.wikipedia.org/wiki/Outline_of_sports'
        :selector: '.mw-content-ltr'
  - :name: 'health'
    :seeds:
      - :url: 'http://en.wikipedia.org/wiki/Health'
        :selector: '.mw-content-ltr'
      - :url: 'http://en.wikipedia.org/wiki/Health_care'
        :selector: '.mw-content-ltr'
  - :name: 'entertainment'
    :seeds:
      - :url: 'http://en.wikipedia.org/wiki/Entertainment'
        :selector: '.mw-content-ltr'
      - :url: 'http://en.wikipedia.org/wiki/Film'
        :selector: '.mw-content-ltr'
      - :url: 'http://en.wikipedia.org/wiki/Radio_programming'
        :selector: '.mw-content-ltr'
      - :url: 'http://en.wikipedia.org/wiki/Concert'
        :selector: '.mw-content-ltr'

:media:
  - :key: 'timeslive.co.za'
    :url: 'http://www.timeslive.co.za'
    :feeds:
      - 'http://avusa.feedsportal.com/c/33051/f/534658/index.rss'
    :selector: '#article .area > h3, #article .area > p, #article > h3'

  - :key: 'thenewage.co.za'
    :url: 'http://www.sowetanlive.co.za'
    :feeds:
      - 'http://thenewage.co.za/rss.aspx?cat_id=9'    # business
      - 'http://thenewage.co.za/rss.aspx?cat_id=1021' # science and technology
      - 'http://thenewage.co.za/rss.aspx?cat_id=1020' # world
      - 'http://thenewage.co.za/rss.aspx?cat_id=1022' # entertainment
      - 'http://thenewage.co.za/rss.aspx?cat_id=1019' # afrika
      - 'http://thenewage.co.za/rss.aspx?cat_id=11'   # sport
    :selector: '#dv_story_dtls'

  - :key: 'sowetanlive.co.za'
    :url: 'http://www.sowetanlive.co.za'
    :feeds:
      - 'http://www.sowetanlive.co.za/?service=rss'
    :selector: '#content .articleheader h3, #content p'

  - :key: 'news24.com'
    :url: 'http://www.news24.com'
    :feeds:
      - 'http://feeds.news24.com/articles/Kenya/TopStories/rss'      # top stories
      - 'http://feeds.news24.com/articles/Kenya/Africa/rss'          # afrika
      - 'http://feeds.news24.com/articles/Kenya/World/rss'           # world
      - 'http://feeds.news24.com/articles/Kenya/SciTech/rss'         # sci-tech
      - 'http://feeds.24.com/articles/sport/featured/topstories/rss' # sport
      - 'http://feeds.news24.com/articles/Kenya/Entertainment/rss'   # entertainment
    :selector: '.article_body p:first'

  - :key: 'iol.co.za'
    :url: 'http://www.iol.co.za'
    :feeds:
      - 'http://iol.co.za/cmlink/1.640'                    # news
      - 'http://www.iol.co.za/cmlink/1.730910'             # business
      - 'http://iol.co.za/cmlink/sport-category-rss-1.704' # sport
    :selector: '.aticle_column > p'

  - :key: 'ewn.co.za'
    :url: 'http://www.ewn.co.za'
    :feeds:
      - 'http://www.ewn.co.za/Feeds/Local.aspx'         # local
      - 'http://www.ewn.co.za/Feeds/World.aspx'         # world
      - 'http://www.ewn.co.za/Feeds/Sport.aspx'         # sport
      - 'http://www.ewn.co.za/Feeds/Entertainment.aspx' # entertainment
      - 'http://www.ewn.co.za/Feeds/Breaking.aspx'      # breaking news
      - 'http://www.ewn.co.za/Feeds/LatestNews.aspx'    # latest news (all categories)
    :selector: '.storybodytext > p'

  - :key: 'mg.co.za'
    :url: 'http://mg.co.za'
    :feeds:
      - 'http://mg.co.za/rss'                         # top stories
      - 'http://mg.co.za/rss/national'                # national
      - 'http://mg.co.za/rss/sport'                   # sport
      - 'http://mg.co.za/rss/business'                # business
      - 'http://mg.co.za/rss/world'                   # world
      - 'http://mg.co.za/rss/africa'                  # africa
      - 'http://mg.co.za/rss/and-in-other-news'       # other
    :selector: '#storycontainer .article_lead, #storycontainer .article_body'
